pipeline{
       agent any
       tools {
          maven "3.6.3"
          jdk   "17.0.9"
     }
       stages {
          stage("compile and run"){
            steps {
              sh  "mvn clean install"
              }
            }
            
          stage('deploy') { 
            
            steps {
                sh "mvn package"
            }
        }
          stage('Build Docker image'){
          
            steps {
                echo "Hello Java Express"
                sh 'ls'
                sh 'docker build -t  prajwal1612/java_PracticeProject:${BUILD_NUMBER} .'
            }
        }
          stage('Docker Login'){
            
            steps {
                 withCredentials([string(credentialsId: 'DockerId', variable: 'Dockerpwd')]) {
                    sh "docker login -u anvbhaskar -p ${Dockerpwd}"
                }
            }                
        }
        stage('Docker Push'){
            steps {
                sh 'docker push prajwal1612/java_PracticeProject:${BUILD_NUMBER}'
            }
        }
        stage('Docker deploy'){
            steps {
               
                sh 'docker run -itd -p  8081:8080 prajwal1612/java_PracticeProject:${BUILD_NUMBER}'
            }
        }
        stage('Archving') { 
            steps {
                 archiveArtifacts '**/target/*.jar'
            }
        }
    }
}
          